---
- hosts: all

  tasks:

  - name: "Install prerequisite packages"
    apt:
            pkg:
                    - docker-compose

  - name: "Telechargement onlyoffice github"
    ansible.builtin.git:
            repo: 'https://github.com/ONLYOFFICE/Docker-CommunityServer'
            dest: /root/Docker-CommunityServer
            version: v11.6.0.1620

  - name: "Creation fichier docker-compose"
    copy:
            src: /root/Docker-CommunityServer/docker-compose.groups.yml
            dest: /root/Docker-CommunityServer/docker-compose.yml

  - name: "start docker compose"
    community.docker.docker_compose:
            project_name: Docker-CommunityServer
            project_src: /root/Docker-CommunityServer/
            state: present

  - name: "recup nom de IP"
    shell: hostname -I | cut -d ' ' -f 1
    register:  IP_ADDRESS
  - name: "recup FQDN"
    shell: curl -sk "https://revprx.ikoula.com/index.php?r=wsds/GetServerNameByIp&IP="{{ IP_ADDRESS.stdout }} | awk -F ':' '{ print $4}' | tr -d '}' | tr -d '"' | tr '[:upper:]' '[:lower:]'
    register: FQDN

  - name: "Installation lets-encrypt"
    community.docker.docker_container_exec:
            container: onlyoffice-community-server
            argv:
                    - /bin/bash
                    - "-c"
                    - "/var/www/onlyoffice/Tools/letsencrypt.sh {{ FQDN.stdout }}"
    register: letsencypt
    until: letsencypt.rc != 0
    retries: 5
    delay: 160
