---
- name: "LAMP stack installation (with one MySQL DB and User)"
  hosts: all
  remote_user: root

  tasks: 

  - name: "Update apt cache"
    apt: update_cache=yes

  - name: "Install LAMP packages"
    apt: name={{ item }} state=present
    with_items:
      - apache2
      - mysql-server
      - php-mysql
      - php
      - libapache2-mod-php
      - python-mysqldb

  - name: "Create mysql database"
    mysql_db: name={{ MYSQL_USER_DB }} state=present

  - name: "Create mysql user"
    mysql_user: 
      name={{ MYSQL_USER }} 
      password={{ MYSQL_USER_PASS }} 
      priv=*.*:ALL
...
