---
- hosts: all

  vars:
    myhostname: "{{ fqdn }}"
    mydomain: "{{ domain_name }}"
    relayhost: ""
    inet_interfaces: all
    smtp_bind_address: ""
    inet_protocols: ipv4


  tasks:
    - name: postfix | install
      apt: pkg=postfix state=latest update_cache=yes
      tags: postfix

    - name: postfix | configure
      lineinfile: dest=/etc/postfix/main.cf regexp="{{ item.regexp }}" line="{{ item.line }}" backup=yes
      with_items:
          - { regexp: "^myorigin", line: "myorigin = {{ mydomain }}" }
          - { regexp: "^relayhost", line: "relayhost = {{ relayhost }}" }
          - { regexp: "^inet_interfaces", line: "inet_interfaces = {{ inet_interfaces }}" }
          - { regexp: "^virtual_maps =", line: "virtual_maps = hash:/etc/aliases" }
          - { regexp: "^home_mailbox =", line: "home_mailbox = Maildir/"}
      notify: reload postfix
      tags: postfix

    - name: postfix | configure
      lineinfile: dest=/etc/postfix/main.cf regexp="{{ item }}" backup=yes state=absent
      with_items:
          - "^myhostname"
      notify: reload postfix
      tags: postfix
      
    - name: postfix | configure
      lineinfile: dest=/etc/postfix/main.cf regexp="^inet_protocols=" line="inet_protocols={{ inet_protocols }}" backup=yes
      notify: restart postfix
      tags: postfix

    - name: postfix | setup smtp bind address
      lineinfile: dest=/etc/postfix/master.cf regexp="^{{ item }}\s+unix" insertafter="^{{ item }}\s+unix" line="{{ item }}      unix  -       -       -       -       -       smtp -o smtp_bind_address={{ smtp_bind_address }}" backup=yes
      with_items:
          - smtp
          - relay
      when: smtp_bind_address != ""
      notify: reload postfix
      tags: postfix

    - name: postfix | ensure service is running
      service: name=postfix state=started
      tags: postfix

  handlers:

    - name: reload postfix
      service: name=postfix state=reloaded

    - name: restart postfix
      service: name=postfix state=restarted