---
- hosts: all

  vars:
    inet_interfaces: all
    inet_protocols: all

  tasks:
    - name: postfix | install
      apt: pkg=postfix state=latest update_cache=yes
      tags: postfix

    - name: postfix | configure
      lineinfile: dest=/etc/postfix/main.cf regexp="{{ item.regexp }}" line="{{ item.line }}" backup=yes
      with_items:
          - { regexp: "^myorigin", line: "myorigin = {{ DOMAIN_NAME }}" }
          - { regexp: "^inet_interfaces", line: "inet_interfaces = {{ inet_interfaces }}" }
          - { regexp: "^virtual_maps =", line: "virtual_maps = hash:/etc/aliases" }
          - { regexp: "^myhostname =", line: "myhostname = {{ FQDN }}"}
          - { regexp: "^mynetworks =", line: "mynetworks = 127.0.0.0/8 [::ffff:127.0.0.0]/104 [::1]/128 {{ MYNETWORKS }}"}
      notify: reload postfix
      tags: postfix
      
    - name: postfix | configure
      lineinfile: dest=/etc/postfix/main.cf regexp="^inet_protocols=" line="inet_protocols={{ inet_protocols }}" backup=yes
      notify: restart postfix
      tags: postfix

    - name: postfix | ensure service is running
      service: name=postfix state=started
      tags: postfix

  handlers:

    - name: reload postfix
      service: name=postfix state=reloaded

    - name: restart postfix
      service: name=postfix state=restarted