---
- name: Copy Jicofo config file.
  template:
    dest: /etc/jitsi/jicofo/config
    src: jicofo_config.j2
    owner: root
    group: root
    mode: "0644"
  notify: restart jicofo

- name: Copy Jitsi Videobridge config file.
  template:
    dest: /etc/jitsi/videobridge/config
    src: videobridge_config.j2
    owner: root
    group: root
    mode: "0644"
  notify: restart jitsi-videobridge

- name: Set Jicofo log level.
  lineinfile:
    dest: /etc/jitsi/jicofo/logging.properties
    regexp: '^\.level'
    line: ".level={{ jitsi_meet_jicofo_loglevel }}"
    state: present
  notify: restart jicofo

- name: Copy Jitsi sip-communicator.properties file
  template:
    dest: /etc/jitsi/videobridge/sip-communicator.properties
    src: sip-communicator.properties.j2
    owner: jvb
    group: jitsi
    mode: "0644"
  notify: restart jitsi-videobridge

- name: Set the hostname in /etc/hosts
  lineinfile:
    dest: /etc/hosts
    line: "127.0.0.1 {{ ansible_hostname }}"
  notify: restart jitsi-videobridge
  