---
- name: Install dokuwiki
  hosts: all
  user: root
  
  roles:
   - { role: nginx, configuration_file: 'roles/dokuwiki/templates/default.conf', dest: dokuwiki }
   - php7.3-fpm
   - dokuwiki