---
- name: "ISPConfig3 installation"
  hosts: all
  remote_user: root

  tasks:

  - name: "Unattended installation of postfix"
    debconf:
      name: postfix
      question: postfix/main_mailer_type
      value: 'Internet Site'
      vtype: string


  - name: "Installation of the many prerequisite packages"
    apt: name={{ item }} update_cache=yes state=present
    with_items:
      - postfix
      - postfix-doc
      - postfix-mysql
      - postgrey
      - mariadb-client
      - mariadb-server
      - openssl
      - getmail4
      - rkhunter
      - binutils
      - dovecot-imapd
      - dovecot-pop3d
      - dovecot-mysql
      - dovecot-sieve
      - dovecot-lmtpd
      - spamassassin
      - clamav
      - clamav-daemon
      - clamav-docs
      - zoo
      - unzip
      - bzip2
      - arj
      - nomarch
      - lzop
      - cabextract
      - apt-listchanges
      - libnet-ldap-perl
      - libauthen-sasl-perl
      - libio-string-perl
      - libio-socket-ssl-perl
      - libnet-ident-perl
      - zip
      - libnet-dns-perl
      - libdbd-mysql-perl
      - pure-ftpd-common
      - pure-ftpd-mysql
      - quota
      - quotatool
      - bind9
      - dnsutils
      - fail2ban
      - patch
      - apache2
      - apache2-doc
      - apache2-utils
      - libapache2-mod-php
      - php7.1
      - php7.1-common
      - php7.1-gd
      - php7.1-mysql
      - php7.1-imap
      - phpmyadmin
      - php7.1-cli
      - php7.1-cgi
      - libapache2-mod-fcgid
      - apache2-suexec-pristine
      - php-pear
      - php7.1-mcrypt
      - mcrypt
      - imagemagick
      - libruby
      - libapache2-mod-python
      - php7.1-curl
      - php7.1-intl
      - php7.1-pspell
      - php7.1-recode
      - php7.1-sqlite3
      - php7.1-tidy
      - php7.1-xmlrpc
      - php7.1-xsl
      - memcached
      - php-memcache
      - php-imagick
      - php-gettext
      - php7.1-zip
      - php7.1-mbstring
      - memcached
      - libapache2-mod-passenger
      - php7.1-soap

  - name: "Stop and Disable SpamAssassin service"
    service:
      name: "spamassassin"
      state: stopped
      enabled: no

  - name: "Enable some Apache2 modules"
    apache2_module:
      name: "{{ item }}"
      state: present
    with_items:
      - suexec
      - rewrite
      - ssl
      - actions
      - include
      - auth_digest
      - cgi
      - headers

  - name: "Enable virtual chroot"
    lineinfile:
      dest: /etc/default/pure-ftpd-common
      regexp: ^VIRTUAL
      line: 'VIRTUALCHROOT=true'   

  - name: "Restart PureFTP service"
    service:
      name: "pure-ftpd-mysql"
      state: restarted
      enabled: yes

  - name: "Download and unpack ISPconfig3"
    unarchive:
      src: http://www.ispconfig.org/downloads/ISPConfig-3-stable.tar.gz
      dest: "/tmp/"
      remote_src: yes

  - name: "Prepare autoinstall.ini installation files"
    template:
      src: "/tmp/ansible/ispconfig/files/autoinstall.ini.j2"
      dest: /tmp/autoinstall.ini

  - name: "Start ISPConfig Installation"
    command: "php -q install.php --autoinstall=/tmp/autoinstall.ini"
    args:
      chdir: /tmp/ispconfig3_install/install
...
