---
- name: "Install PHP packages/extensions"
  apt: name={{ item }} state=present update_cache=yes
  with_items:
    - php7.1-mysql
    - php7.1
    - php7.1-gd 
    - php-ssh2
    - php7.1-xml
    - php7.1-mcrypt
    - php7.1-opcache
    - php7.1-mbstring
    - php7.1-json
    - php7.1-zip

- name: "Copy PHP.ini configuration file"
  copy:
    src: /tmp/ansible/joomla/roles/php/files/php.ini
    dest: /etc/php/7.1/apache2/php.ini
  notify:
    - restart apache
...
