---
- name: "Install PHP packages/extensions"
  apt: name={{ item }} state=present update_cache=yes
  with_items:
    - php7.2-mysql
    - php7.2
    - php7.2-gd 
    - php7.2-ssh2
    - php7.2-xml
    - php7.2-mcrypt
    - php7.2-opcache
    - php7.2-mbstring
    - php7.2-json
    - php7.2-zip

- name: "Copy PHP.ini configuration file"
  copy:
    src: /tmp/ansible/joomla/roles/php/files/php.ini
    dest: /etc/php/7.2/apache2/php.ini
  notify:
    - restart apache
...
