---
- name: "Docker install"
  hosts: all
  remote_user: root

  tasks:
  - name: "Install prerequies packages :"
    apt: pkg={{ item }} update_cache=no state=present
    with_items:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg2
      - software-properties-common
      - python3-pip

  - name: "Add Docker repo"
    apt_repository: repo='deb https://download.docker.com/linux/debian stretch stable' state=present update_cache=no

  - name: "Add APT key of Docker repo :"
    apt_key: url='https://download.docker.com/linux/debian/gpg' state=present

  - name: "Install Docker packages :"
    apt: pkg={{ item }} update_cache=yes state=present
    with_items:
      - docker-ce

  - name: "Start and enable docker unit"
    service: name=docker state=started enabled=yes

  - name: "Install docker-py pip module"
    pip:
      name: docker-py

  - name: "Run Portainer Container"
    docker_container:
      name: portainer
      image: portainer/portainer
      state: started
      restart_policy: always
      published_ports:
        - 0.0.0.0:9000:9000/tcp
      volumes:
        - /var/lib/docker/portainer:/data
        - /var/run/docker.sock:/var/run/docker.sock

  - name: "Get Ip address of eth0"
    shell: curl -s ifconfig.co
    register: eth0_ipaddress

  - name: Configure admin user password
    uri:
      url: "http://{{ eth0_ipaddress.stdout }}:9000/api/users/admin/init"
      method: POST
      return_content: yes
      body_format: json
      body: {"Username": "admin", "Password": "{{ admin_password }}"}
...
